<#
.SYNOPSIS
    Next.js TypeScript Deployment Script for Windows Server (Robocopy & PM2).

.PARAMETER ReleaseId
    Unique release timestamp generated by the CI workflow.

.PARAMETER SourceDir
    The GitHub Actions runner workspace root directory.

.PARAMETER AppName
    The application process name defined in ecosystem.config.js.

.PARAMETER AppRootDir
    Root directory of the target environment on the Windows host. Defaults to
    the production root.

.PARAMETER Standalone
    Deploy a Next.js standalone build (.next\standalone) instead of the full
    .next + node_modules tree. The standalone folder already carries its own
    traced node_modules and a server.js entry point, so PM2 must be configured
    to run "server.js" rather than "next start" for that environment.
#>

param (
    [Parameter(Mandatory=$true)]
    [string]$ReleaseId,

    [Parameter(Mandatory=$false)]
    [string]$SourceDir = $env:GITHUB_WORKSPACE,

    [Parameter(Mandatory=$false)]
    [string]$AppName = "requisitions_automation",

    [Parameter(Mandatory=$false)]
    [string]$AppRootDir = "C:\requisitions_automation",

    [Parameter(Mandatory=$false)]
    [switch]$Standalone
)

# Stop execution immediately if any command encounters an error
$ErrorActionPreference = "Stop"

# ==============================================================================
# BLOCK 1: PATH DEFINITIONS
# ==============================================================================
$ReleasesDir    = "$AppRootDir\releases"                 # Parent releases folder
$NewReleaseDir  = "$ReleasesDir\release-$ReleaseId"      # Destination path for this release
$JunctionLink   = "$AppRootDir\current"                  # Active junction link consumed by PM2

$DeployMode = if ($Standalone) { "standalone" } else { "full" }

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host " Starting Fast Robocopy Deployment: Release $ReleaseId" -ForegroundColor Cyan
Write-Host " Target: $AppName at $AppRootDir ($DeployMode output)" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

# Ensure master releases directory exists
if (-not (Test-Path $ReleasesDir)) {
    Write-Host "[1/5] Creating master releases folder..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $ReleasesDir -Force | Out-Null
}

New-Item -ItemType Directory -Path $NewReleaseDir -Force | Out-Null

# ==============================================================================
# BLOCK 2: COPY ARTIFACTS INTO RELEASE DIRECTORY
# ==============================================================================
# The runner workspace and the releases folder live on the same host, so the
# artifacts are copied straight across instead of being zipped and immediately
# re-extracted. Robocopy also handles paths longer than MAX_PATH, which deep
# node_modules trees regularly exceed.
#
# .next\cache\turbopack is the Turbopack build cache: compiler scratch
# work that speeds up the NEXT build and is never read at runtime, so it stays
# out of the release. That path only exists under .next, so the exclusion is a
# no-op for the other copied directories.
Write-Host "[2/5] Copying build artifacts and node_modules into $NewReleaseDir..." -ForegroundColor Green

if ($Standalone) {
    # .next\standalone already holds server.js, a traced node_modules and the
    # server half of .next. The workflow copies public and .next\static into it
    # beforehand, because Next.js deliberately leaves those out.
    $StandaloneDir = "$SourceDir\.next\standalone"

    if (-not (Test-Path "$StandaloneDir\server.js")) {
        throw "Standalone build not found at '$StandaloneDir\server.js'. Was the app built with NEXT_OUTPUT_STANDALONE=1?"
    }

    robocopy "$StandaloneDir" "$NewReleaseDir" /E /MT:16 /NFL /NDL /NJH /NJS /NP | Out-Null

    # Robocopy reports success as exit codes 0-7 (1 = files copied); 8 and above is a real failure
    if ($LASTEXITCODE -ge 8) {
        throw "Robocopy failed to copy the standalone bundle into '$NewReleaseDir' with exit code $LASTEXITCODE"
    }

    # Reset so a benign robocopy code (e.g. 1) is not mistaken for a script failure
    $global:LASTEXITCODE = 0
}
else {
    # Include TypeScript Next.js artifacts
    $DirsToCopy  = @(".next", "node_modules")
    $FilesToCopy = @("package.json", "package-lock.json")

    if (Test-Path "$SourceDir\public")         { $DirsToCopy  += "public" }
    if (Test-Path "$SourceDir\next.config.ts") { $FilesToCopy += "next.config.ts" }

    foreach ($Dir in $DirsToCopy) {
        robocopy "$SourceDir\$Dir" "$NewReleaseDir\$Dir" /E /MT:16 /XD "$SourceDir\.next\cache\turbopack" /NFL /NDL /NJH /NJS /NP | Out-Null

        # Robocopy reports success as exit codes 0-7 (1 = files copied); 8 and above is a real failure
        if ($LASTEXITCODE -ge 8) {
            throw "Robocopy failed to copy '$Dir' into '$NewReleaseDir' with exit code $LASTEXITCODE"
        }
    }

    # Reset so a benign robocopy code (e.g. 1) is not mistaken for a script failure
    $global:LASTEXITCODE = 0

    foreach ($File in $FilesToCopy) {
        Copy-Item "$SourceDir\$File" "$NewReleaseDir\$File" -Force
    }
}

# ==============================================================================
# BLOCK 3: ATOMIC WINDOWS JUNCTION SWAP
# ==============================================================================
Write-Host "[3/5] Swapping Windows Junction Link ($JunctionLink -> $NewReleaseDir)..." -ForegroundColor Green

if (Test-Path $JunctionLink) {
    cmd /c rmdir "$JunctionLink"
}

cmd /c mklink /J "$JunctionLink" "$NewReleaseDir"

# ==============================================================================
# BLOCK 4: PM2 ZERO-DOWNTIME RELOAD
# ==============================================================================
Write-Host "[4/5] Executing PM2 reload for app '$AppName'..." -ForegroundColor Green

Set-Location -Path $AppRootDir

# Reload cluster mode app with updated environment settings
pm2 reload ecosystem.config.js --only $AppName --update-env

# ==============================================================================
# BLOCK 5: RELEASE RETENTION CLEANUP
# ==============================================================================
Write-Host "[5/5] Enforcing release retention policy (Keeping 5 newest)..." -ForegroundColor Green

$OldReleases = Get-ChildItem -Path $ReleasesDir -Directory | 
    Sort-Object CreationTime -Descending | 
    Select-Object -Skip 5

foreach ($OldRelease in $OldReleases) {
    Write-Host " -> Removing old release folder: $($OldRelease.FullName)" -ForegroundColor DarkGray
    Remove-Item $OldRelease.FullName -Recurse -Force
}

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host " Deployment Completed Successfully! Release $ReleaseId is LIVE." -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

# The calling workflow step exits with this script's code, and the native
# commands above (robocopy, pm2) leave $LASTEXITCODE set - return success explicitly.
exit 0