import "server-only";
import { Workbook } from "exceljs";

// How a report column is written to Excel. Numbers and dates are written as
// real Excel values with a display format, so auditors can sum, sort and
// filter them; the queries return dates as Excel serials (lib/reports/sql.ts)
// so no JavaScript Date or server time zone is involved.
export type ReportColumnKind =
  | "text" // short text
  | "longtext" // wrapped, wider column (justifications, histories)
  | "integer"
  | "decimal" // one decimal place, e.g. days to decision
  | "money" // KES, thousands separators
  | "date"
  | "datetime";

export type ReportColumn = {
  key: string;
  header: string;
  kind?: ReportColumnKind;
};

export type ReportSheet = {
  name: string;
  columns: ReportColumn[];
  rows: Record<string, unknown>[];
};

const NUM_FMT: Partial<Record<ReportColumnKind, string>> = {
  integer: "0",
  decimal: "0.0",
  money: "#,##0",
  date: "dd mmm yyyy",
  datetime: "dd mmm yyyy hh:mm",
};

const WIDTH: Record<ReportColumnKind, number> = {
  text: 22,
  longtext: 60,
  integer: 12,
  decimal: 12,
  money: 16,
  date: 14,
  datetime: 18,
};

const isNumeric = (kind: ReportColumnKind) =>
  kind !== "text" && kind !== "longtext";

// node-postgres returns BIGINT/NUMERIC as strings; coerce numeric kinds
function cellValue(value: unknown, kind: ReportColumnKind) {
  if (value === null || value === undefined || value === "") return null;
  if (!isNumeric(kind)) return String(value);
  const number = Number(value);
  return Number.isFinite(number) ? number : null;
}

function addReportSheet(workbook: Workbook, sheet: ReportSheet) {
  const worksheet = workbook.addWorksheet(sheet.name, {
    views: [{ state: "frozen", ySplit: 1 }],
  });

  worksheet.columns = sheet.columns.map(({ key, header, kind = "text" }) => ({
    key,
    header,
    width: Math.max(WIDTH[kind], header.length + 2),
    style: {
      numFmt: NUM_FMT[kind],
      alignment:
        kind === "longtext"
          ? { wrapText: true, vertical: "top" }
          : { vertical: "top" },
    },
  }));

  for (const row of sheet.rows) {
    worksheet.addRow(
      Object.fromEntries(
        sheet.columns.map(({ key, kind = "text" }) => [
          key,
          cellValue(row[key], kind),
        ]),
      ),
    );
  }

  const headerRow = worksheet.getRow(1);
  headerRow.font = { bold: true };
  headerRow.alignment = { vertical: "middle", wrapText: true };
  worksheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: sheet.columns.length },
  };
}

export type ReportInfo = {
  title: string;
  rowUnit: string;
  from: string;
  to: string;
  statusLabel: string;
  generatedBy: string;
};

const formatIsoDate = (value: string) =>
  new Date(`${value}T00:00:00Z`).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    timeZone: "UTC",
  });

// Every workbook ends with a "Report Info" sheet saying what was pulled,
// by whom and when, so a file passed around later still explains itself.
function addInfoSheet(workbook: Workbook, info: ReportInfo, sheets: ReportSheet[]) {
  const worksheet = workbook.addWorksheet("Report Info");
  worksheet.columns = [{ width: 24 }, { width: 60 }];

  const generatedAt = new Date().toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "Africa/Nairobi",
  });

  const rows: [string, string][] = [
    ["Report", info.title],
    ["Submitted from", formatIsoDate(info.from)],
    ["Submitted to", `${formatIsoDate(info.to)} (inclusive)`],
    ["Status filter", info.statusLabel],
    ["Rows", info.rowUnit],
    ...sheets.map(
      (sheet): [string, string] => [`${sheet.name} rows`, String(sheet.rows.length)],
    ),
    ["Generated by", info.generatedBy],
    ["Generated at", `${generatedAt} (Africa/Nairobi)`],
    ["Time zone", "All dates and times are Africa/Nairobi time"],
  ];

  worksheet.addRows(rows);
  worksheet.getColumn(1).font = { bold: true };
}

export async function buildReportWorkbook(
  sheets: ReportSheet[],
  info: ReportInfo,
) {
  const workbook = new Workbook();
  workbook.creator = "Hotpoint Apps Hub";
  workbook.created = new Date();

  for (const sheet of sheets) addReportSheet(workbook, sheet);
  addInfoSheet(workbook, info, sheets);

  return workbook.xlsx.writeBuffer();
}
